name: 'Setup Anchor'
description: 'Install Anchor, Solana CLI tools, and Node.js.'
branding:
  icon: anchor
  color: blue
inputs:
  node-version:
    description: 'Version of node.js to use'
    required: false
    default: '22.14.0'
  solana-cli-version:
    description: 'Version of Solana CLI to use'
    required: false
    default: '2.0.21'
  anchor-version:
    description: 'Version of Anchor to use'
    required: false
    default: '0.31.1'
  use-avm:
    description: 'Use Anchor Version Manager to install instead of npm'
    required: false
    default: "false"

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Output Node Version
      id: node_v
      shell: bash
      run: |
        echo "node_v=$(node -v)" >> $GITHUB_OUTPUT
    
    - name: Setup Solana
      uses: heyAyushh/setup-solana@v5.9
      with:
        solana-cli-version: ${{ inputs.solana-cli-version }}
    
    # Clean existing anchor installation
    - name: Clean existing Anchor installation
      run: |
        rm -rf ~/.cargo/bin/anchor
        rm -rf ~/.avm
      shell: bash
    
    # Cache Anchor specific items with version and week in key
    - uses: actions/cache@v4
      id: cache-anchor
      with:
        path: |
          ~/.cargo/bin/anchor
          ~/.avm
          /opt/hostedtoolcache/node
        key: anchor-${{ runner.os }}-${{ inputs.anchor-version }}-node-${{ steps.node_v.outputs.node_v }}-solana-${{ inputs.solana-cli-version }}-$(date +%Y%V)
    
    - name: Install Anchor
      if: steps.cache-anchor.outputs.cache-hit != 'true'
      run: |
        echo "Installing Anchor via npm..."
        npm i -g @coral-xyz/anchor-cli@${{ inputs.anchor-version }}
        
        # Check if anchor command exists after npm install
        if ! command -v anchor &> /dev/null; then
          echo "anchor command not found after npm install."
          
          echo "Installing Anchor via AVM..."
          cargo install --git https://github.com/coral-xyz/anchor avm
          avm install ${{ inputs.anchor-version }}
          avm use ${{ inputs.anchor-version }}
          
          if ! command -v anchor &> /dev/null; then
            echo "anchor command not found after avm use."
            
            echo "Installing Anchor directly via cargo..."
            cargo install --git https://github.com/coral-xyz/anchor --tag v${{ inputs.anchor-version }} anchor-cli
          fi
        fi

        if ! command -v anchor &> /dev/null; then
          echo "ERROR: Failed to install anchor command using multiple methods."
          exit 1
        else
          echo "anchor command successfully installed."
          anchor --version
        fi
      shell: bash