name: 'Setup Anchor'
description: 'Install Anchor, Solana CLI tools, and Node.js.'
branding:
  icon: anchor
  color: blue
inputs:
  node-version:
    description: 'Version of node.js to use'
    required: false
    default: '16.15.1' # LTS
  solana-cli-version:
    description: 'Version of Solana CLI to use'
    required: false
    default: '1.17.1' 
  anchor-version:
    description: 'Version of Anchor to use'
    required: false
    default: '0.29.0' # latest
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Setup Solana
      uses: heyAyushh/setup-solana@v5.2
      with:
        solana-cli-version: ${{ inputs.solana-cli-version }}
    - uses: actions/cache@v4
      id: cache-anchor
      with:
        path: |
          ~/.cargo/bin
          ~/.avm
          ${{ steps.install-anchor.outputs.anchor-dir }}
        key: anchor-cli-${{ runner.os }}-build-${{ inputs.anchor-version }}
    - name: Install Anchor
      id: install-anchor
      if: steps.cache-anchor.outputs.cache-hit != 'true'
      run: |
        if [ ${{ runner.os }} == 'Linux' -a $$ ${{ runner.arch }} == "X86" -o ${{ runner.arch }} == "X64" $$ ]; then
            npm i -g @coral-xyz/anchor-cli@${{ inputs.anchor-version }}
            anchor_dir=$(dirname "$(which anchor)")
            echo "::set-output name=anchor-dir::$anchor_dir"
        else
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install ${{ inputs.anchor-version }}
          avm use ${{ inputs.anchor-version }}
        fi
      shell: bash
