name: 'Setup Anchor'
description: 'Install Anchor, Solana CLI tools, and Node.js.'
branding:
  icon: anchor
  color: blue
inputs:
  node-version:
    description: 'Version of node.js to use'
    required: false
    default: '20.15.0' # LTS
  solana-cli-version:
    description: 'Version of Solana CLI to use'
    required: false
    default: '1.18.17' 
  anchor-version:
    description: 'Version of Anchor to use'
    required: false
    default: '0.30.1' # latest
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Output Node Version
      id: node_v
      shell: bash
      run: |
        echo "node_v=$(node -v)" >> $GITHUB_OUTPUT
    - name: Setup Solana
      uses: heyAyushh/setup-solana@v5.4
      with:
        solana-cli-version: ${{ inputs.solana-cli-version }}
    - uses: actions/cache@v4
      id: cache-anchor
      with:
        path: |
          ~/.cargo/bin
          ~/.avm
          /opt/hostedtoolcache/node
        key: anchor-cli-${{ runner.os }}-build-${{ inputs.anchor-version }}-${{ steps.node_v.outputs.node_v }}
    - name: Install Anchor
      id: install-anchor
      if: steps.cache-anchor.outputs.cache-hit != 'true'
      run: |
        if [[ "${{ runner.os }}" == "Linux" && ("${{ runner.arch }}" == "X86" || "${{ runner.arch }}" == "X64") ]]; then
            npm i -g @coral-xyz/anchor-cli@${{ inputs.anchor-version }}
        else
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install ${{ inputs.anchor-version }}
          avm use ${{ inputs.anchor-version }}
        fi
      shell: bash
